import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const fintechs = [
  // ============ BUILDING ON SEISMIC ============
  {
    name: "Specie Finance",
    slug: "specie-finance",
    logoColor: "#D0A0B7",
    abbrev: "SP",
    description: "Global neobank for trade finance. Single account replacing 4+ traditional bank accounts.",
    longDescription: "Led by Frankie DiGiacomo (ex-Morgan Stanley). Provides unified liquidity, built-in controls, and local payments for importers/exporters across 124+ countries.",
    founded: 2024,
    headquarters: "New York",
    country: "US",
    region: "Global",
    website: "https://specie.finance",
    category: "neobank",
    subcategory: "trade-finance",
    annualVolume: 850000000,
    totalUsers: 125000,
    employees: 25,
    totalFunding: 5000000,
    lastFundingRound: "Seed",
    investors: ["Seismic"],
    painPoints: ["fragmented_banking", "cash_trapped", "no_fx_control", "manual_compliance"],
    seismicStatus: "integrated",
    integrationNote: "Live on Seismic - Privacy for trade finance",
    privacyScore: 95,
    integrationPotential: 100,
    primaryMarkets: ["US", "EU", "LATAM", "ASIA"],
    usersByCountry: { "US": 40000, "UK": 20000, "Brazil": 15000, "Mexico": 10000 }
  },
  {
    name: "Cred",
    slug: "cred",
    logoColor: "#00D897",
    abbrev: "CR",
    description: "Private credit service for frontier businesses using proprietary credit analytics.",
    longDescription: "Led by Julian Gay (sold company to AppDirect). Backed by Alliance DAO. Provides fast working capital to businesses that traditional finance overlooks.",
    founded: 2023,
    headquarters: "San Francisco",
    country: "US",
    region: "Global",
    website: "https://cred.finance",
    category: "lending",
    subcategory: "private-credit",
    annualVolume: 500000000,
    totalUsers: 50000,
    employees: 30,
    totalFunding: 8000000,
    lastFundingRound: "Seed",
    investors: ["Alliance DAO", "Seismic"],
    painPoints: ["data_exposure", "slow_underwriting", "public_loan_terms"],
    seismicStatus: "integrated",
    integrationNote: "Live on Seismic - Encrypted lending rails",
    privacyScore: 98,
    integrationPotential: 100,
    primaryMarkets: ["US", "EU", "Africa", "LATAM"],
    usersByCountry: { "US": 20000, "Nigeria": 8000, "Kenya": 5000, "Brazil": 7000 }
  },
  
  // ============ PAYMENTS ============
  {
    name: "Stripe",
    slug: "stripe",
    logoColor: "#635BFF",
    abbrev: "ST",
    description: "Global payment processing infrastructure powering millions of internet businesses.",
    longDescription: "Founded by Patrick and John Collison. Processes hundreds of billions annually. Used by Amazon, Google, Shopify, and millions of startups.",
    founded: 2010,
    headquarters: "San Francisco",
    country: "US",
    region: "Global",
    website: "https://stripe.com",
    category: "payments",
    subcategory: "processing",
    annualVolume: 817000000000,
    totalUsers: 4000000,
    monthlyActiveUsers: 2000000,
    employees: 8000,
    totalFunding: 8700000000,
    lastFundingRound: "Series I",
    lastFundingAmount: 6500000000,
    valuation: 50000000000,
    investors: ["Sequoia", "Andreessen Horowitz", "General Catalyst", "Tiger Global"],
    painPoints: ["public_transaction_data", "merchant_exposure", "competitive_intel_leak"],
    seismicStatus: "potential",
    integrationNote: "High potential - B2B payments need privacy",
    privacyScore: 75,
    integrationPotential: 70,
    primaryMarkets: ["US", "EU", "UK", "Canada", "Australia"],
    usersByCountry: { "US": 2000000, "UK": 400000, "EU": 600000, "Canada": 200000 }
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    logoColor: "#072654",
    abbrev: "RP",
    description: "India's leading payment gateway with full-stack financial solutions.",
    longDescription: "Founded by Harshil Mathur and Shashank Kumar. Processes over $180B annually for 8M+ businesses in India.",
    founded: 2014,
    headquarters: "Bangalore",
    country: "India",
    region: "Asia",
    website: "https://razorpay.com",
    category: "payments",
    subcategory: "gateway",
    annualVolume: 180000000000,
    totalUsers: 8000000,
    employees: 3000,
    totalFunding: 741000000,
    lastFundingRound: "Series F",
    valuation: 7500000000,
    investors: ["Sequoia India", "Tiger Global", "Y Combinator", "GIC"],
    painPoints: ["public_merchant_data", "transaction_visibility", "competitive_exposure"],
    seismicStatus: "potential",
    integrationNote: "Ideal for private merchant settlements in India",
    privacyScore: 80,
    integrationPotential: 75,
    primaryMarkets: ["India"],
    usersByCountry: { "India": 8000000 }
  },
  {
    name: "Wise",
    slug: "wise",
    logoColor: "#00B9FF",
    abbrev: "WI",
    description: "International money transfers at real exchange rates without hidden fees.",
    longDescription: "Founded by Kristo Käärmann and Taavet Hinrikus. Moves £9B monthly across borders for 16M+ customers.",
    founded: 2011,
    headquarters: "London",
    country: "UK",
    region: "Global",
    website: "https://wise.com",
    category: "payments",
    subcategory: "remittance",
    annualVolume: 105000000000,
    totalUsers: 16000000,
    monthlyActiveUsers: 6000000,
    employees: 5000,
    totalFunding: 1300000000,
    lastFundingRound: "IPO",
    valuation: 11000000000,
    investors: ["Andreessen Horowitz", "Balderton Capital", "IA Ventures"],
    painPoints: ["cross_border_tracking", "recipient_exposure", "corridor_visibility"],
    seismicStatus: "potential",
    integrationNote: "Perfect for encrypted cross-border rails",
    privacyScore: 85,
    integrationPotential: 80,
    primaryMarkets: ["UK", "EU", "US", "Australia", "Asia"],
    usersByCountry: { "UK": 4000000, "EU": 4000000, "US": 3000000, "Australia": 1500000 }
  },
  {
    name: "Adyen",
    slug: "adyen",
    logoColor: "#0ABF53",
    abbrev: "AD",
    description: "Enterprise payment platform for global unified commerce.",
    longDescription: "Dutch fintech processing €767B annually. Powers payments for Netflix, Uber, Spotify, Microsoft, and major enterprises.",
    founded: 2006,
    headquarters: "Amsterdam",
    country: "Netherlands",
    region: "Global",
    website: "https://adyen.com",
    category: "payments",
    subcategory: "enterprise",
    annualVolume: 767000000000,
    totalUsers: 5000,
    employees: 4000,
    totalFunding: 266000000,
    lastFundingRound: "IPO",
    valuation: 45000000000,
    investors: ["General Atlantic", "Temasek", "Index Ventures"],
    painPoints: ["enterprise_data_exposure", "merchant_analytics_leak", "volume_visibility"],
    seismicStatus: "potential",
    integrationNote: "Enterprise encrypted settlement rails",
    privacyScore: 70,
    integrationPotential: 65,
    primaryMarkets: ["EU", "US", "UK", "Asia"],
    usersByCountry: { "EU": 2000, "US": 1500, "UK": 800, "Asia": 700 }
  },
  {
    name: "Square",
    slug: "square",
    logoColor: "#006AFF",
    abbrev: "SQ",
    description: "Financial services and digital payments company for small businesses.",
    longDescription: "Founded by Jack Dorsey. Provides POS systems, Cash App, and business banking. Renamed to Block Inc.",
    founded: 2009,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://squareup.com",
    category: "payments",
    subcategory: "pos",
    annualVolume: 186000000000,
    totalUsers: 56000000,
    employees: 12000,
    totalFunding: 590000000,
    lastFundingRound: "IPO",
    valuation: 42000000000,
    investors: ["Sequoia", "Khosla Ventures", "Visa"],
    painPoints: ["smb_transaction_exposure", "cash_app_visibility", "merchant_data_public"],
    seismicStatus: "potential",
    integrationNote: "SMB payments privacy layer",
    privacyScore: 72,
    integrationPotential: 60,
    primaryMarkets: ["US", "Canada", "UK", "Australia", "Japan"],
    usersByCountry: { "US": 40000000, "UK": 5000000, "Canada": 4000000, "Australia": 3000000 }
  },
  {
    name: "PayPal",
    slug: "paypal",
    logoColor: "#003087",
    abbrev: "PP",
    description: "Global online payments system supporting online money transfers.",
    longDescription: "One of the world's largest payment platforms with 430M+ active accounts. Owns Venmo, Braintree, and Xoom.",
    founded: 1998,
    headquarters: "San Jose",
    country: "US",
    region: "Global",
    website: "https://paypal.com",
    category: "payments",
    subcategory: "digital-wallet",
    annualVolume: 1360000000000,
    totalUsers: 430000000,
    monthlyActiveUsers: 200000000,
    employees: 27000,
    totalFunding: 0,
    lastFundingRound: "IPO",
    valuation: 70000000000,
    investors: ["Public"],
    painPoints: ["transaction_history_exposure", "venmo_social_feed", "merchant_tracking"],
    seismicStatus: "potential",
    integrationNote: "Consumer payment privacy upgrade",
    privacyScore: 65,
    integrationPotential: 50,
    primaryMarkets: ["US", "EU", "UK", "Australia", "Asia"],
    usersByCountry: { "US": 180000000, "EU": 80000000, "UK": 30000000, "Asia": 50000000 }
  },
  {
    name: "Airwallex",
    slug: "airwallex",
    logoColor: "#E6194B",
    abbrev: "AW",
    description: "Global payments platform for modern businesses with multi-currency accounts.",
    longDescription: "Australian fintech processing $235B+ annually. Provides cards, FX, and embedded finance for 200K+ businesses.",
    founded: 2015,
    headquarters: "Melbourne",
    country: "Australia",
    region: "Global",
    website: "https://airwallex.com",
    category: "payments",
    subcategory: "business-payments",
    annualVolume: 235000000000,
    totalUsers: 200000,
    employees: 1500,
    totalFunding: 902000000,
    lastFundingRound: "Series E",
    valuation: 5500000000,
    investors: ["DST Global", "Tencent", "Sequoia China", "Salesforce Ventures"],
    painPoints: ["cross_border_visibility", "fx_exposure", "business_flow_tracking"],
    seismicStatus: "potential",
    integrationNote: "Strong fit for encrypted business payments",
    privacyScore: 78,
    integrationPotential: 75,
    primaryMarkets: ["Australia", "UK", "EU", "Asia", "US"],
    usersByCountry: { "Australia": 50000, "UK": 40000, "Asia": 60000, "EU": 30000, "US": 20000 }
  },
  {
    name: "Checkout.com",
    slug: "checkout-com",
    logoColor: "#0A0A0A",
    abbrev: "CO",
    description: "Cloud-based payment processing for enterprise merchants.",
    longDescription: "UK fintech valued at $40B. Processes payments for Netflix, Klarna, Coinbase, and major global brands.",
    founded: 2012,
    headquarters: "London",
    country: "UK",
    region: "Global",
    website: "https://checkout.com",
    category: "payments",
    subcategory: "enterprise",
    annualVolume: 250000000000,
    totalUsers: 50000,
    employees: 2000,
    totalFunding: 1800000000,
    lastFundingRound: "Series D",
    valuation: 40000000000,
    investors: ["Tiger Global", "Insight Partners", "DST Global", "Coatue"],
    painPoints: ["enterprise_volume_exposure", "merchant_data_leak", "transaction_analytics"],
    seismicStatus: "potential",
    integrationNote: "Enterprise privacy infrastructure",
    privacyScore: 73,
    integrationPotential: 68,
    primaryMarkets: ["UK", "EU", "US", "MENA"],
    usersByCountry: { "UK": 15000, "EU": 15000, "US": 10000, "MENA": 10000 }
  },

  // ============ NEOBANKS ============
  {
    name: "Revolut",
    slug: "revolut",
    logoColor: "#0066FF",
    abbrev: "RV",
    description: "Digital banking with trading, crypto, and international spending.",
    longDescription: "UK neobank with 35M+ customers. Offers banking, stock trading, crypto, and international transfers in one app.",
    founded: 2015,
    headquarters: "London",
    country: "UK",
    region: "Global",
    website: "https://revolut.com",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 230000000000,
    totalUsers: 35000000,
    monthlyActiveUsers: 20000000,
    employees: 8000,
    totalFunding: 1700000000,
    lastFundingRound: "Series E",
    valuation: 33000000000,
    investors: ["SoftBank", "Tiger Global", "DST Global", "Schroders"],
    painPoints: ["account_visibility", "spending_tracking", "crypto_exposure"],
    seismicStatus: "potential",
    integrationNote: "Strong candidate for private transaction layer",
    privacyScore: 80,
    integrationPotential: 72,
    primaryMarkets: ["UK", "EU", "US", "Australia"],
    usersByCountry: { "UK": 8000000, "EU": 15000000, "US": 5000000, "Australia": 2000000 }
  },
  {
    name: "Nubank",
    slug: "nubank",
    logoColor: "#820AD1",
    abbrev: "NU",
    description: "Latin America's largest digital bank serving 85M+ customers.",
    longDescription: "Brazilian fintech disrupting traditional banking in LATAM. Offers credit cards, accounts, loans, and investments.",
    founded: 2013,
    headquarters: "São Paulo",
    country: "Brazil",
    region: "LATAM",
    website: "https://nubank.com.br",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 320000000000,
    totalUsers: 85000000,
    monthlyActiveUsers: 60000000,
    employees: 7000,
    totalFunding: 2800000000,
    lastFundingRound: "IPO",
    valuation: 45000000000,
    investors: ["Sequoia", "DST Global", "Tencent", "Berkshire Hathaway"],
    painPoints: ["transaction_transparency", "credit_exposure", "spending_patterns"],
    seismicStatus: "potential",
    integrationNote: "Massive privacy potential in LATAM market",
    privacyScore: 82,
    integrationPotential: 78,
    primaryMarkets: ["Brazil", "Mexico", "Colombia"],
    usersByCountry: { "Brazil": 70000000, "Mexico": 10000000, "Colombia": 5000000 }
  },
  {
    name: "Chime",
    slug: "chime",
    logoColor: "#1EC677",
    abbrev: "CH",
    description: "Fee-free mobile banking with early paycheck access.",
    longDescription: "US neobank with 21M+ customers. No monthly fees, overdraft fees, or minimum balances. Automatic savings features.",
    founded: 2012,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://chime.com",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 150000000000,
    totalUsers: 21000000,
    monthlyActiveUsers: 12000000,
    employees: 2000,
    totalFunding: 2300000000,
    lastFundingRound: "Series G",
    valuation: 25000000000,
    investors: ["DST Global", "General Atlantic", "Tiger Global", "Sequoia"],
    painPoints: ["paycheck_visibility", "spending_exposure", "savings_tracking"],
    seismicStatus: "potential",
    integrationNote: "Consumer banking privacy integration",
    privacyScore: 76,
    integrationPotential: 65,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 21000000 }
  },
  {
    name: "N26",
    slug: "n26",
    logoColor: "#36A18B",
    abbrev: "N26",
    description: "European mobile bank with instant notifications and spending insights.",
    longDescription: "German neobank operating across Europe with 8M+ customers. Full banking license with deposit protection.",
    founded: 2013,
    headquarters: "Berlin",
    country: "Germany",
    region: "EU",
    website: "https://n26.com",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 90000000000,
    totalUsers: 8000000,
    monthlyActiveUsers: 4000000,
    employees: 1500,
    totalFunding: 1700000000,
    lastFundingRound: "Series E",
    valuation: 9000000000,
    investors: ["Insight Partners", "Tencent", "Allianz", "Peter Thiel"],
    painPoints: ["eu_transaction_tracking", "cross_border_visibility", "spending_analytics"],
    seismicStatus: "potential",
    integrationNote: "EU banking privacy layer",
    privacyScore: 79,
    integrationPotential: 70,
    primaryMarkets: ["Germany", "France", "Spain", "Italy", "Austria"],
    usersByCountry: { "Germany": 3000000, "France": 1500000, "Spain": 1000000, "Italy": 800000 }
  },
  {
    name: "Monzo",
    slug: "monzo",
    logoColor: "#FF5A5F",
    abbrev: "MZ",
    description: "UK digital bank with instant spending notifications and budgeting.",
    longDescription: "British challenger bank with 8M+ customers. Known for coral debit card and user-friendly app.",
    founded: 2015,
    headquarters: "London",
    country: "UK",
    region: "UK",
    website: "https://monzo.com",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 75000000000,
    totalUsers: 8000000,
    monthlyActiveUsers: 5000000,
    employees: 3000,
    totalFunding: 1000000000,
    lastFundingRound: "Series H",
    valuation: 4500000000,
    investors: ["Y Combinator", "Accel", "General Catalyst", "Passion Capital"],
    painPoints: ["spending_categorization_exposure", "merchant_tracking", "salary_visibility"],
    seismicStatus: "potential",
    integrationNote: "UK consumer privacy banking",
    privacyScore: 77,
    integrationPotential: 68,
    primaryMarkets: ["UK"],
    usersByCountry: { "UK": 8000000 }
  },
  {
    name: "SoFi",
    slug: "sofi",
    logoColor: "#00D4B5",
    abbrev: "SF",
    description: "Digital financial services including loans, banking, and investing.",
    longDescription: "US fintech offering student loan refinancing, mortgages, personal loans, credit cards, investing, and banking.",
    founded: 2011,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://sofi.com",
    category: "neobank",
    subcategory: "full-stack",
    annualVolume: 120000000000,
    totalUsers: 6500000,
    monthlyActiveUsers: 3000000,
    employees: 5000,
    totalFunding: 3000000000,
    lastFundingRound: "IPO",
    valuation: 8000000000,
    investors: ["SoftBank", "Silver Lake", "Qatar Investment Authority"],
    painPoints: ["loan_data_exposure", "investment_tracking", "credit_history_visibility"],
    seismicStatus: "potential",
    integrationNote: "Full-stack fintech privacy opportunity",
    privacyScore: 74,
    integrationPotential: 62,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 6500000 }
  },
  {
    name: "Current",
    slug: "current",
    logoColor: "#000000",
    abbrev: "CU",
    description: "Mobile banking for modern life with faster direct deposits.",
    longDescription: "US mobile bank targeting underbanked consumers with no hidden fees and instant spending notifications.",
    founded: 2015,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://current.com",
    category: "neobank",
    subcategory: "consumer",
    annualVolume: 40000000000,
    totalUsers: 4000000,
    employees: 500,
    totalFunding: 400000000,
    lastFundingRound: "Series D",
    valuation: 2200000000,
    investors: ["Andreessen Horowitz", "Tiger Global", "QED Investors"],
    painPoints: ["underbanked_data_exposure", "paycheck_tracking", "spending_visibility"],
    seismicStatus: "potential",
    integrationNote: "Privacy for underbanked populations",
    privacyScore: 75,
    integrationPotential: 70,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 4000000 }
  },

  // ============ LENDING ============
  {
    name: "Klarna",
    slug: "klarna",
    logoColor: "#FFB3C7",
    abbrev: "KL",
    description: "Buy now, pay later leader serving 150M consumers globally.",
    longDescription: "Swedish fintech offering flexible payment options at checkout. Partners with 500K+ retailers worldwide.",
    founded: 2005,
    headquarters: "Stockholm",
    country: "Sweden",
    region: "Global",
    website: "https://klarna.com",
    category: "lending",
    subcategory: "bnpl",
    annualVolume: 80000000000,
    totalUsers: 150000000,
    monthlyActiveUsers: 50000000,
    employees: 5000,
    totalFunding: 4500000000,
    lastFundingRound: "Series H",
    valuation: 6700000000,
    investors: ["SoftBank", "Sequoia", "Silver Lake", "Commonwealth Bank"],
    painPoints: ["purchase_history_exposure", "bnpl_tracking", "merchant_data_sharing"],
    seismicStatus: "potential",
    integrationNote: "BNPL data privacy opportunity",
    privacyScore: 83,
    integrationPotential: 75,
    primaryMarkets: ["Sweden", "US", "UK", "Germany", "Australia"],
    usersByCountry: { "US": 40000000, "UK": 18000000, "Germany": 15000000, "Sweden": 5000000 }
  },
  {
    name: "Affirm",
    slug: "affirm",
    logoColor: "#0FA0EA",
    abbrev: "AF",
    description: "Transparent buy now, pay later with no hidden fees.",
    longDescription: "Founded by PayPal co-founder Max Levchin. Partners with Amazon, Shopify, and major retailers for point-of-sale financing.",
    founded: 2012,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://affirm.com",
    category: "lending",
    subcategory: "bnpl",
    annualVolume: 44000000000,
    totalUsers: 14000000,
    employees: 2500,
    totalFunding: 1500000000,
    lastFundingRound: "IPO",
    valuation: 15000000000,
    investors: ["Khosla Ventures", "Lightspeed", "Spark Capital", "Thrive Capital"],
    painPoints: ["loan_terms_visibility", "purchase_tracking", "credit_exposure"],
    seismicStatus: "potential",
    integrationNote: "Consumer lending privacy rails",
    privacyScore: 80,
    integrationPotential: 72,
    primaryMarkets: ["US", "Canada"],
    usersByCountry: { "US": 12000000, "Canada": 2000000 }
  },
  {
    name: "Afterpay",
    slug: "afterpay",
    logoColor: "#B2FCE4",
    abbrev: "AP",
    description: "Buy now, pay later service acquired by Block (Square).",
    longDescription: "Australian BNPL pioneer now part of Block Inc. 20M+ active customers shopping at 100K+ merchants.",
    founded: 2014,
    headquarters: "Melbourne",
    country: "Australia",
    region: "Global",
    website: "https://afterpay.com",
    category: "lending",
    subcategory: "bnpl",
    annualVolume: 25000000000,
    totalUsers: 20000000,
    employees: 1500,
    totalFunding: 0,
    lastFundingRound: "Acquired",
    valuation: 29000000000,
    investors: ["Block Inc (acquired)"],
    painPoints: ["shopping_history_exposure", "payment_tracking", "merchant_analytics"],
    seismicStatus: "potential",
    integrationNote: "BNPL privacy within Block ecosystem",
    privacyScore: 78,
    integrationPotential: 65,
    primaryMarkets: ["Australia", "US", "UK", "NZ"],
    usersByCountry: { "Australia": 6000000, "US": 10000000, "UK": 3000000, "NZ": 1000000 }
  },
  {
    name: "LendingClub",
    slug: "lendingclub",
    logoColor: "#002F6C",
    abbrev: "LC",
    description: "America's largest online lending marketplace.",
    longDescription: "Pioneered peer-to-peer lending, now a full-spectrum fintech bank. $80B+ in loans originated.",
    founded: 2006,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://lendingclub.com",
    category: "lending",
    subcategory: "marketplace",
    annualVolume: 12000000000,
    totalUsers: 4000000,
    employees: 1200,
    totalFunding: 1300000000,
    lastFundingRound: "IPO",
    valuation: 2000000000,
    investors: ["Foundation Capital", "Norwest Venture Partners", "Canaan Partners"],
    painPoints: ["loan_data_public", "borrower_exposure", "investor_tracking"],
    seismicStatus: "potential",
    integrationNote: "P2P lending privacy layer",
    privacyScore: 81,
    integrationPotential: 73,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 4000000 }
  },
  {
    name: "Upgrade",
    slug: "upgrade",
    logoColor: "#1E90FF",
    abbrev: "UG",
    description: "Credit products including cards and personal loans.",
    longDescription: "Founded by Renaud Laplanche (LendingClub founder). Offers credit cards with fixed payments and personal loans.",
    founded: 2016,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://upgrade.com",
    category: "lending",
    subcategory: "consumer",
    annualVolume: 8000000000,
    totalUsers: 3000000,
    employees: 1000,
    totalFunding: 600000000,
    lastFundingRound: "Series F",
    valuation: 6000000000,
    investors: ["Ribbit Capital", "Union Square Ventures", "Vy Capital"],
    painPoints: ["credit_history_exposure", "payment_tracking", "debt_visibility"],
    seismicStatus: "potential",
    integrationNote: "Consumer credit privacy",
    privacyScore: 77,
    integrationPotential: 70,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 3000000 }
  },
  {
    name: "Brex",
    slug: "brex",
    logoColor: "#F46036",
    abbrev: "BX",
    description: "Corporate cards and spend management for startups and enterprises.",
    longDescription: "Brazilian founders built corporate cards requiring no personal guarantee. Now offers full spend management.",
    founded: 2017,
    headquarters: "San Francisco",
    country: "US",
    region: "North America",
    website: "https://brex.com",
    category: "lending",
    subcategory: "corporate",
    annualVolume: 50000000000,
    totalUsers: 30000,
    employees: 1500,
    totalFunding: 1200000000,
    lastFundingRound: "Series D",
    valuation: 12000000000,
    investors: ["Greenoaks", "Tiger Global", "Y Combinator", "Ribbit Capital"],
    painPoints: ["corporate_spend_visibility", "vendor_exposure", "budget_tracking"],
    seismicStatus: "potential",
    integrationNote: "Corporate spend privacy for startups",
    privacyScore: 84,
    integrationPotential: 78,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 30000 }
  },
  {
    name: "Ramp",
    slug: "ramp",
    logoColor: "#E9C46A",
    abbrev: "RM",
    description: "Corporate cards with built-in expense management and savings.",
    longDescription: "Fastest-growing fintech in US history. Helps companies save 5% on average through spend insights.",
    founded: 2019,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://ramp.com",
    category: "lending",
    subcategory: "corporate",
    annualVolume: 30000000000,
    totalUsers: 25000,
    employees: 1000,
    totalFunding: 1600000000,
    lastFundingRound: "Series D",
    valuation: 8100000000,
    investors: ["Founders Fund", "Stripe", "D1 Capital", "Coatue"],
    painPoints: ["expense_visibility", "vendor_tracking", "budget_exposure"],
    seismicStatus: "potential",
    integrationNote: "Expense privacy for high-growth companies",
    privacyScore: 82,
    integrationPotential: 76,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 25000 }
  },

  // ============ CRYPTO / WEB3 ============
  {
    name: "Coinbase",
    slug: "coinbase",
    logoColor: "#0052FF",
    abbrev: "CB",
    description: "Largest US cryptocurrency exchange by trading volume.",
    longDescription: "Public company (NASDAQ: COIN) with 110M+ verified users. Offers trading, custody, staking, and Web3 wallet.",
    founded: 2012,
    headquarters: "San Francisco",
    country: "US",
    region: "Global",
    website: "https://coinbase.com",
    category: "crypto",
    subcategory: "exchange",
    annualVolume: 830000000000,
    totalUsers: 110000000,
    monthlyActiveUsers: 9000000,
    employees: 4700,
    totalFunding: 679000000,
    lastFundingRound: "IPO",
    valuation: 55000000000,
    investors: ["Andreessen Horowitz", "Union Square Ventures", "Tiger Global"],
    painPoints: ["on_chain_transparency", "wallet_tracking", "trade_history_public"],
    seismicStatus: "potential",
    integrationNote: "Crypto exchange privacy layer",
    privacyScore: 88,
    integrationPotential: 70,
    primaryMarkets: ["US", "UK", "EU", "Japan"],
    usersByCountry: { "US": 50000000, "UK": 10000000, "EU": 20000000, "Japan": 5000000 }
  },
  {
    name: "Kraken",
    slug: "kraken",
    logoColor: "#5741D9",
    abbrev: "KR",
    description: "US cryptocurrency exchange known for security and margin trading.",
    longDescription: "Founded by Jesse Powell. One of the oldest exchanges, known for proof-of-reserves and security focus.",
    founded: 2011,
    headquarters: "San Francisco",
    country: "US",
    region: "Global",
    website: "https://kraken.com",
    category: "crypto",
    subcategory: "exchange",
    annualVolume: 207000000000,
    totalUsers: 10000000,
    monthlyActiveUsers: 2000000,
    employees: 3400,
    totalFunding: 129000000,
    lastFundingRound: "Series C",
    valuation: 11000000000,
    investors: ["Tribe Capital", "Hummingbird Ventures", "Blockchain Capital"],
    painPoints: ["trade_visibility", "wallet_exposure", "withdrawal_tracking"],
    seismicStatus: "potential",
    integrationNote: "Privacy-first crypto exchange integration",
    privacyScore: 85,
    integrationPotential: 73,
    primaryMarkets: ["US", "EU", "Canada", "Australia"],
    usersByCountry: { "US": 4000000, "EU": 3000000, "Canada": 1000000, "Australia": 500000 }
  },
  {
    name: "Blockchain.com",
    slug: "blockchain-com",
    logoColor: "#121D33",
    abbrev: "BC",
    description: "Crypto wallet and exchange with 85M+ wallet users.",
    longDescription: "One of the oldest Bitcoin companies. Provides wallet, exchange, and explorer services.",
    founded: 2011,
    headquarters: "London",
    country: "UK",
    region: "Global",
    website: "https://blockchain.com",
    category: "crypto",
    subcategory: "wallet",
    annualVolume: 40000000000,
    totalUsers: 85000000,
    employees: 500,
    totalFunding: 540000000,
    lastFundingRound: "Series D",
    valuation: 14000000000,
    investors: ["Lightspeed", "VY Capital", "Google Ventures"],
    painPoints: ["wallet_balance_exposure", "transaction_history_public", "address_tracking"],
    seismicStatus: "potential",
    integrationNote: "Wallet privacy layer",
    privacyScore: 86,
    integrationPotential: 75,
    primaryMarkets: ["Global"],
    usersByCountry: { "US": 20000000, "EU": 15000000, "UK": 10000000, "Asia": 20000000 }
  },
  {
    name: "Gemini",
    slug: "gemini",
    logoColor: "#00DCFA",
    abbrev: "GM",
    description: "Regulated crypto exchange founded by Winklevoss twins.",
    longDescription: "New York-based exchange with strong compliance focus. Offers trading, custody, and credit card.",
    founded: 2014,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://gemini.com",
    category: "crypto",
    subcategory: "exchange",
    annualVolume: 30000000000,
    totalUsers: 13000000,
    employees: 1000,
    totalFunding: 425000000,
    lastFundingRound: "Unknown",
    valuation: 7100000000,
    investors: ["Morgan Creek Digital"],
    painPoints: ["regulated_but_transparent", "trade_reporting", "custody_visibility"],
    seismicStatus: "potential",
    integrationNote: "Compliance + privacy for institutions",
    privacyScore: 80,
    integrationPotential: 72,
    primaryMarkets: ["US", "UK", "EU", "Singapore"],
    usersByCountry: { "US": 8000000, "UK": 2000000, "EU": 2000000, "Singapore": 1000000 }
  },
  {
    name: "Circle",
    slug: "circle",
    logoColor: "#00D395",
    abbrev: "CI",
    description: "Issuer of USDC stablecoin with $30B+ in circulation.",
    longDescription: "Major stablecoin issuer and Web3 infrastructure company. USDC is second-largest stablecoin by market cap.",
    founded: 2013,
    headquarters: "Boston",
    country: "US",
    region: "Global",
    website: "https://circle.com",
    category: "crypto",
    subcategory: "stablecoin",
    annualVolume: 500000000000,
    totalUsers: 5000000,
    employees: 1000,
    totalFunding: 1100000000,
    lastFundingRound: "Series F",
    valuation: 9000000000,
    investors: ["BlackRock", "Fidelity", "Marshall Wace", "Fin Capital"],
    painPoints: ["usdc_flows_visible", "mint_burn_tracking", "settlement_exposure"],
    seismicStatus: "potential",
    integrationNote: "Private stablecoin rails",
    privacyScore: 90,
    integrationPotential: 85,
    primaryMarkets: ["Global"],
    usersByCountry: { "US": 2000000, "EU": 1000000, "Asia": 1500000, "LATAM": 500000 }
  },

  // ============ INFRASTRUCTURE / DATA ============
  {
    name: "Plaid",
    slug: "plaid",
    logoColor: "#000000",
    abbrev: "PL",
    description: "Financial data network connecting 8000+ apps to bank accounts.",
    longDescription: "Powers connections for Venmo, Robinhood, Coinbase, and thousands more. 100M+ linked accounts.",
    founded: 2013,
    headquarters: "San Francisco",
    country: "US",
    region: "Global",
    website: "https://plaid.com",
    category: "infrastructure",
    subcategory: "data",
    annualVolume: 0,
    totalUsers: 100000000,
    employees: 1500,
    totalFunding: 740000000,
    lastFundingRound: "Series D",
    valuation: 13400000000,
    investors: ["Kleiner Perkins", "NEA", "Andreessen Horowitz", "Index Ventures"],
    painPoints: ["bank_data_aggregation", "account_linking_exposure", "transaction_scraping"],
    seismicStatus: "potential",
    integrationNote: "Data aggregation privacy layer",
    privacyScore: 92,
    integrationPotential: 80,
    primaryMarkets: ["US", "UK", "EU", "Canada"],
    usersByCountry: { "US": 70000000, "UK": 10000000, "EU": 15000000, "Canada": 5000000 }
  },
  {
    name: "MX",
    slug: "mx",
    logoColor: "#1E3A5F",
    abbrev: "MX",
    description: "Financial data platform for banks and fintechs.",
    longDescription: "Provides data enhancement, analytics, and connectivity for 2000+ banks and fintechs.",
    founded: 2010,
    headquarters: "Lehi",
    country: "US",
    region: "North America",
    website: "https://mx.com",
    category: "infrastructure",
    subcategory: "data",
    annualVolume: 0,
    totalUsers: 50000000,
    employees: 600,
    totalFunding: 505000000,
    lastFundingRound: "Series C",
    valuation: 1900000000,
    investors: ["TPG", "Digital Garage", "Pelion Venture Partners"],
    painPoints: ["financial_data_exposure", "bank_connectivity", "analytics_visibility"],
    seismicStatus: "potential",
    integrationNote: "Financial data privacy infrastructure",
    privacyScore: 88,
    integrationPotential: 75,
    primaryMarkets: ["US", "Canada"],
    usersByCountry: { "US": 45000000, "Canada": 5000000 }
  },
  {
    name: "Marqeta",
    slug: "marqeta",
    logoColor: "#000000",
    abbrev: "MQ",
    description: "Modern card issuing platform for fintechs.",
    longDescription: "Powers cards for Square, DoorDash, Affirm, and more. Processes $200B+ annually.",
    founded: 2010,
    headquarters: "Oakland",
    country: "US",
    region: "Global",
    website: "https://marqeta.com",
    category: "infrastructure",
    subcategory: "card-issuing",
    annualVolume: 200000000000,
    totalUsers: 100,
    employees: 700,
    totalFunding: 528000000,
    lastFundingRound: "IPO",
    valuation: 4000000000,
    investors: ["Goldman Sachs", "Visa", "Iconiq Capital", "83North"],
    painPoints: ["card_transaction_visibility", "merchant_tracking", "spend_exposure"],
    seismicStatus: "potential",
    integrationNote: "Private card issuing rails",
    privacyScore: 79,
    integrationPotential: 72,
    primaryMarkets: ["US", "EU", "Australia"],
    usersByCountry: { "US": 60, "EU": 25, "Australia": 15 }
  },

  // ============ INSURANCE ============
  {
    name: "Lemonade",
    slug: "lemonade",
    logoColor: "#FF0080",
    abbrev: "LM",
    description: "AI-powered insurance for renters, homeowners, car, pet, and life.",
    longDescription: "Uses AI for instant claims and policies. B Corp with Giveback program donating unclaimed premiums.",
    founded: 2015,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://lemonade.com",
    category: "insurance",
    subcategory: "multi-line",
    annualVolume: 500000000,
    totalUsers: 2000000,
    employees: 1200,
    totalFunding: 480000000,
    lastFundingRound: "IPO",
    valuation: 2000000000,
    investors: ["SoftBank", "Sequoia", "Allianz", "General Catalyst"],
    painPoints: ["claims_data_exposure", "policy_tracking", "personal_info_aggregation"],
    seismicStatus: "potential",
    integrationNote: "Insurance data privacy",
    privacyScore: 75,
    integrationPotential: 60,
    primaryMarkets: ["US", "Germany", "Netherlands", "France"],
    usersByCountry: { "US": 1500000, "Germany": 200000, "Netherlands": 100000, "France": 100000 }
  },
  {
    name: "Root Insurance",
    slug: "root-insurance",
    logoColor: "#000000",
    abbrev: "RT",
    description: "Usage-based car insurance using smartphone telematics.",
    longDescription: "Prices insurance based on actual driving behavior captured through mobile app.",
    founded: 2015,
    headquarters: "Columbus",
    country: "US",
    region: "North America",
    website: "https://joinroot.com",
    category: "insurance",
    subcategory: "auto",
    annualVolume: 700000000,
    totalUsers: 400000,
    employees: 1500,
    totalFunding: 1200000000,
    lastFundingRound: "IPO",
    valuation: 800000000,
    investors: ["DST Global", "Tiger Global", "Redpoint", "Ribbit Capital"],
    painPoints: ["driving_data_exposure", "location_tracking", "behavior_analytics"],
    seismicStatus: "potential",
    integrationNote: "Telematics data privacy",
    privacyScore: 85,
    integrationPotential: 68,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 400000 }
  },

  // ============ WEALTH / INVESTING ============
  {
    name: "Robinhood",
    slug: "robinhood",
    logoColor: "#00C805",
    abbrev: "RH",
    description: "Commission-free trading app that democratized investing.",
    longDescription: "Pioneered zero-commission trading. 23M+ funded accounts with stocks, options, and crypto trading.",
    founded: 2013,
    headquarters: "Menlo Park",
    country: "US",
    region: "North America",
    website: "https://robinhood.com",
    category: "wealth",
    subcategory: "trading",
    annualVolume: 120000000000,
    totalUsers: 23000000,
    monthlyActiveUsers: 11000000,
    employees: 2600,
    totalFunding: 5600000000,
    lastFundingRound: "IPO",
    valuation: 20000000000,
    investors: ["Sequoia", "NEA", "Ribbit Capital", "DST Global"],
    painPoints: ["trade_history_exposure", "portfolio_tracking", "order_flow_visibility"],
    seismicStatus: "potential",
    integrationNote: "Retail trading privacy",
    privacyScore: 78,
    integrationPotential: 65,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 23000000 }
  },
  {
    name: "Wealthfront",
    slug: "wealthfront",
    logoColor: "#A879FE",
    abbrev: "WF",
    description: "Automated investing and financial planning platform.",
    longDescription: "Pioneer in robo-advising with $50B+ AUM. Offers investment accounts, high-yield cash, and planning tools.",
    founded: 2008,
    headquarters: "Palo Alto",
    country: "US",
    region: "North America",
    website: "https://wealthfront.com",
    category: "wealth",
    subcategory: "robo-advisor",
    annualVolume: 50000000000,
    totalUsers: 700000,
    employees: 500,
    totalFunding: 275000000,
    lastFundingRound: "Series F",
    valuation: 1400000000,
    investors: ["Benchmark", "Index Ventures", "Greylock Partners", "DAG Ventures"],
    painPoints: ["investment_exposure", "portfolio_visibility", "net_worth_tracking"],
    seismicStatus: "potential",
    integrationNote: "Wealth management privacy",
    privacyScore: 76,
    integrationPotential: 62,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 700000 }
  },
  {
    name: "Betterment",
    slug: "betterment",
    logoColor: "#1C6EE3",
    abbrev: "BT",
    description: "Largest independent robo-advisor in the US.",
    longDescription: "Manages $40B+ with automated investing, tax-loss harvesting, and retirement planning.",
    founded: 2008,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://betterment.com",
    category: "wealth",
    subcategory: "robo-advisor",
    annualVolume: 40000000000,
    totalUsers: 800000,
    employees: 400,
    totalFunding: 435000000,
    lastFundingRound: "Series F",
    valuation: 1300000000,
    investors: ["Kinnevik", "Bessemer Venture Partners", "Francisco Partners"],
    painPoints: ["retirement_data_exposure", "investment_tracking", "tax_info_visibility"],
    seismicStatus: "potential",
    integrationNote: "Retirement privacy protection",
    privacyScore: 74,
    integrationPotential: 60,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 800000 }
  },
  {
    name: "Acorns",
    slug: "acorns",
    logoColor: "#6AC58C",
    abbrev: "AC",
    description: "Micro-investing app that rounds up purchases to invest spare change.",
    longDescription: "10M+ users investing spare change automatically. Also offers checking, retirement, and kids accounts.",
    founded: 2012,
    headquarters: "Irvine",
    country: "US",
    region: "North America",
    website: "https://acorns.com",
    category: "wealth",
    subcategory: "micro-investing",
    annualVolume: 15000000000,
    totalUsers: 10000000,
    monthlyActiveUsers: 5000000,
    employees: 500,
    totalFunding: 507000000,
    lastFundingRound: "Series F",
    valuation: 1900000000,
    investors: ["BlackRock", "NBCUniversal", "PayPal", "DST Global"],
    painPoints: ["spending_round_up_tracking", "investment_visibility", "linked_account_exposure"],
    seismicStatus: "potential",
    integrationNote: "Micro-investing privacy",
    privacyScore: 72,
    integrationPotential: 58,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 10000000 }
  },
  {
    name: "Public",
    slug: "public",
    logoColor: "#000000",
    abbrev: "PB",
    description: "Social investing platform for stocks, ETFs, and crypto.",
    longDescription: "Combines investing with social features. Users can share portfolios and follow other investors.",
    founded: 2019,
    headquarters: "New York",
    country: "US",
    region: "North America",
    website: "https://public.com",
    category: "wealth",
    subcategory: "social-trading",
    annualVolume: 5000000000,
    totalUsers: 3000000,
    employees: 300,
    totalFunding: 310000000,
    lastFundingRound: "Series D",
    valuation: 1200000000,
    investors: ["Accel", "Tiger Global", "Greycroft", "Will Smith"],
    painPoints: ["social_portfolio_exposure", "trade_sharing", "follower_tracking"],
    seismicStatus: "potential",
    integrationNote: "Social trading with selective privacy",
    privacyScore: 70,
    integrationPotential: 65,
    primaryMarkets: ["US"],
    usersByCountry: { "US": 3000000 }
  },
  {
    name: "eToro",
    slug: "etoro",
    logoColor: "#1ABC9C",
    abbrev: "ET",
    description: "Social trading platform with copy trading features.",
    longDescription: "30M+ users worldwide. Known for CopyTrader feature to automatically replicate successful traders.",
    founded: 2007,
    headquarters: "Tel Aviv",
    country: "Israel",
    region: "Global",
    website: "https://etoro.com",
    category: "wealth",
    subcategory: "social-trading",
    annualVolume: 200000000000,
    totalUsers: 30000000,
    employees: 2500,
    totalFunding: 573000000,
    lastFundingRound: "Series E",
    valuation: 3500000000,
    investors: ["SoftBank", "ION Group", "Spark Capital", "China Minsheng"],
    painPoints: ["copy_trading_exposure", "portfolio_public", "trade_signal_visibility"],
    seismicStatus: "potential",
    integrationNote: "Social trading privacy options",
    privacyScore: 68,
    integrationPotential: 55,
    primaryMarkets: ["UK", "EU", "Australia", "US"],
    usersByCountry: { "UK": 8000000, "EU": 12000000, "Australia": 3000000, "US": 2000000 }
  },

  // ============ EMERGING MARKETS ============
  {
    name: "Paytm",
    slug: "paytm",
    logoColor: "#00BAF2",
    abbrev: "PT",
    description: "India's leading digital payments and financial services company.",
    longDescription: "Over 350M registered users. Offers payments, banking, lending, insurance, and wealth management.",
    founded: 2010,
    headquarters: "Noida",
    country: "India",
    region: "Asia",
    website: "https://paytm.com",
    category: "payments",
    subcategory: "super-app",
    annualVolume: 150000000000,
    totalUsers: 350000000,
    monthlyActiveUsers: 80000000,
    employees: 10000,
    totalFunding: 4700000000,
    lastFundingRound: "IPO",
    valuation: 15000000000,
    investors: ["SoftBank", "Ant Group", "Berkshire Hathaway", "SAIF Partners"],
    painPoints: ["upi_transaction_visibility", "merchant_tracking", "wallet_exposure"],
    seismicStatus: "potential",
    integrationNote: "India payments privacy layer",
    privacyScore: 82,
    integrationPotential: 68,
    primaryMarkets: ["India"],
    usersByCountry: { "India": 350000000 }
  },
  {
    name: "PhonePe",
    slug: "phonepe",
    logoColor: "#5F259F",
    abbrev: "PE",
    description: "India's top UPI payment app owned by Walmart.",
    longDescription: "500M+ registered users processing 50% of India's UPI transactions. Acquired by Walmart via Flipkart.",
    founded: 2015,
    headquarters: "Bangalore",
    country: "India",
    region: "Asia",
    website: "https://phonepe.com",
    category: "payments",
    subcategory: "upi",
    annualVolume: 300000000000,
    totalUsers: 500000000,
    monthlyActiveUsers: 200000000,
    employees: 5000,
    totalFunding: 850000000,
    lastFundingRound: "Private",
    valuation: 12000000000,
    investors: ["Walmart", "General Atlantic", "Tiger Global", "Tencent"],
    painPoints: ["upi_flow_visibility", "merchant_data", "payment_tracking"],
    seismicStatus: "potential",
    integrationNote: "UPI privacy infrastructure",
    privacyScore: 84,
    integrationPotential: 70,
    primaryMarkets: ["India"],
    usersByCountry: { "India": 500000000 }
  },
  {
    name: "Mercado Pago",
    slug: "mercado-pago",
    logoColor: "#00A650",
    abbrev: "MP",
    description: "Latin America's largest fintech by MercadoLibre.",
    longDescription: "60M+ active users across LATAM. Offers payments, lending, insurance, and crypto services.",
    founded: 2004,
    headquarters: "Buenos Aires",
    country: "Argentina",
    region: "LATAM",
    website: "https://mercadopago.com",
    category: "payments",
    subcategory: "super-app",
    annualVolume: 160000000000,
    totalUsers: 60000000,
    employees: 3000,
    totalFunding: 0,
    lastFundingRound: "MercadoLibre subsidiary",
    valuation: 0,
    investors: ["MercadoLibre (parent)"],
    painPoints: ["latam_payment_tracking", "merchant_visibility", "lending_exposure"],
    seismicStatus: "potential",
    integrationNote: "LATAM fintech privacy rails",
    privacyScore: 80,
    integrationPotential: 72,
    primaryMarkets: ["Argentina", "Brazil", "Mexico", "Chile", "Colombia"],
    usersByCountry: { "Brazil": 25000000, "Argentina": 15000000, "Mexico": 10000000, "Chile": 5000000 }
  },
  {
    name: "GCash",
    slug: "gcash",
    logoColor: "#007DFE",
    abbrev: "GC",
    description: "Philippines' leading mobile wallet with 80M+ users.",
    longDescription: "Owned by Globe Telecom and Ant Group. Dominant in Philippines mobile payments and financial services.",
    founded: 2004,
    headquarters: "Manila",
    country: "Philippines",
    region: "Asia",
    website: "https://gcash.com",
    category: "payments",
    subcategory: "mobile-wallet",
    annualVolume: 90000000000,
    totalUsers: 80000000,
    monthlyActiveUsers: 60000000,
    employees: 2000,
    totalFunding: 300000000,
    lastFundingRound: "Series F",
    valuation: 5000000000,
    investors: ["Ant Group", "Warburg Pincus", "Bow Wave Capital"],
    painPoints: ["mobile_wallet_tracking", "p2p_visibility", "merchant_payments"],
    seismicStatus: "potential",
    integrationNote: "Southeast Asia privacy fintech",
    privacyScore: 81,
    integrationPotential: 73,
    primaryMarkets: ["Philippines"],
    usersByCountry: { "Philippines": 80000000 }
  },
  {
    name: "GoPay",
    slug: "gopay",
    logoColor: "#00AED6",
    abbrev: "GP",
    description: "Indonesia's leading e-wallet by GoTo Group.",
    longDescription: "Part of GoTo ecosystem (Gojek + Tokopedia). 40M+ monthly transacting users.",
    founded: 2016,
    headquarters: "Jakarta",
    country: "Indonesia",
    region: "Asia",
    website: "https://gopay.co.id",
    category: "payments",
    subcategory: "mobile-wallet",
    annualVolume: 70000000000,
    totalUsers: 40000000,
    monthlyActiveUsers: 30000000,
    employees: 1000,
    totalFunding: 0,
    lastFundingRound: "GoTo subsidiary",
    valuation: 0,
    investors: ["GoTo Group (parent)"],
    painPoints: ["super_app_tracking", "payment_visibility", "merchant_data"],
    seismicStatus: "potential",
    integrationNote: "Indonesia super-app privacy",
    privacyScore: 79,
    integrationPotential: 70,
    primaryMarkets: ["Indonesia"],
    usersByCountry: { "Indonesia": 40000000 }
  }
]

async function main() {
  console.log('Starting seed...')
  
  for (const fintech of fintechs) {
    const created = await prisma.fintech.upsert({
      where: { slug: fintech.slug },
      update: fintech,
      create: fintech,
    })
    console.log(`Created/Updated: ${created.name}`)
  }
  
  console.log(`Seeded ${fintechs.length} fintechs`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
